AllCops:
  DisabledByDefault: true
  Exclude:
    - '{bin,pkg,tmp,vendor}/**/*' # vendored dependencies etc.
    - 'lib/regexp_parser/scanner.rb' # Ragel-generated code
  NewCops: enable
  RubyInterpreters:
    - ruby
    - rake
  SuggestExtensions: false
  TargetRubyVersion: 2.0

Lint:
  Enabled: true

Lint/UselessConstantScoping:
  Enabled: false

# ignore weird looking regexps in specs, we have these on purpose
Lint/DuplicateRegexpCharacterClassElement:
  Exclude: ['spec/**/*']
Lint/MixedRegexpCaptureTypes:
  Exclude: ['spec/**/*']
