language: ruby

env:
  - RAGEL=ON

before_install:
  - gem update
  - gem --version
  - travis_retry sudo apt-get update -qq
  - travis_retry bash -c "if [[ \"${RAGEL}\" == ON ]]; then sudo apt-get install -qq ragel; fi"

rvm:
  # travis defaults to the latest patch version if only the minor version is given
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

matrix:
  allow_failures:
    - rvm: 'ruby-head'

script: 'bundle exec rake test:full'
