language: ruby

branches:
  only:
    - master

env:
  - RAGEL=ON

before_install:
  - gem update --system
  - gem install bundler
  - gem update
  - gem --version
  - travis_retry sudo apt-get update -qq
  - travis_retry bash -c "if [[ \"${RAGEL}\" == ON ]]; then sudo apt-get install -qq ragel; fi"

rvm:
  # travis defaults to the latest patch version if only the minor version is given
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head

script: 'bundle exec rake test:full'
