# based on https://github.com/rails/rails/blob/4a78dcb/.github/workflows/rubocop.yml

name: rubocop linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true
    # Create a dummy scanner.rb so we don't need Ragel but require statements work
    - name: Stub scanner.rb
      run: 'echo "class Regexp::Scanner; end" > lib/regexp_parser/scanner.rb'
    - name: Run rubocop
      run: bundle exec rubocop
